/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene-transformed.glb --instance --transform-all -ts 
Files: scene-transformed.glb [920.54KB] > /home/necron/Web/rasta-rock-ecommerce/apps/next/public/models/Guitar/scene-transformed-transformed.glb [235.97KB] (74%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Action' | 'Empty.004Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_6: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_27: THREE.Mesh
    Object_36: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(
    '/scene-transformed-transformed.glb'
  ) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='GLTF_SceneRootNode' position={[0.479, 0, -0.018]} scale={0.267}>
          <group name='Empty004_19' position={[-1.8, 0.771, 0.195]} rotation={[0, 0.406, 0]}>
            <group name='Empty003_18' position={[0, -1.142, 0]} rotation={[0, -1.277, 1.103]}>
              <group name='Cube001_4' position={[3.41, 0.6, -0.04]} rotation={[0.2, 0.577, -0.356]}>
                <mesh
                  name='Object_8'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <group name='Cube002_5' rotation={[-0.054, 0, -0.71]} scale={[0.195, 0.195, 0.124]}>
                <mesh
                  name='Object_11'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <group name='Cube003_6' position={[0.688, 0.396, -0.015]}>
                <mesh
                  name='Object_13'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <group name='Cube004_7' position={[0.221, 0.412, 0.03]}>
                <mesh
                  name='Object_15'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <group name='Cube005_8' position={[0.522, -0.028, 0.027]}>
                <mesh
                  name='Object_18'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.PaletteMaterial001}
                />
                <mesh
                  name='Object_19'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.PaletteMaterial002}
                />
              </group>
              <group name='Cube006_9' position={[1.47, 0.401, 0.037]}>
                <mesh
                  name='Object_21'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.PaletteMaterial003}
                />
              </group>
              <group name='Cube_3' position={[0.706, 0.409, 0.013]} scale={[1, 1, 0.621]}>
                <mesh
                  name='Object_6'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.PaletteMaterial004}
                />
              </group>
              <group name='cuerdas001_11' position={[2.055, 0.323, -0.195]} scale={[0.793, 1, 1]}>
                <mesh
                  name='Object_23'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <group name='cuerpo_guitarra_12' position={[1.8, 0.371, -0.195]}>
                <mesh
                  name='Object_25'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.PaletteMaterial002}
                />
              </group>
              <group
                name='Cylinder001_14'
                position={[0.415, 0.161, 0.097]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.06}
              >
                <mesh
                  name='Object_29'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.PaletteMaterial002}
                />
              </group>
              <group name='Cylinder002_15' position={[0.263, 0.708, 0.049]}>
                <mesh
                  name='Object_31'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.PaletteMaterial001}
                />
                <mesh
                  name='Object_32'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.PaletteMaterial002}
                />
              </group>
              <group
                name='Cylinder003_16'
                position={[1.668, 0.954, -0.088]}
                rotation={[0, 0, -0.888]}
                scale={0.032}
              >
                <mesh
                  name='Object_34'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.PaletteMaterial004}
                />
              </group>
              <group
                name='Cylinder_13'
                position={[3.474, 0.468, -0.013]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.023, 0.012, 0.023]}
              >
                <mesh
                  name='Object_27'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
              <group name='Plane_17' position={[-0.021, -0.04, 0.018]}>
                <mesh
                  name='Object_36'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.PaletteMaterial001}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed-transformed.glb')
