/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf --transform -ts 
Files: scene.gltf [47.96KB] > /home/necron/Web/rasta-rock-ecommerce/apps/next/public/models/AbstractBg/scene-transformed.glb [2.76MB] (-5655%)
Author: ParuthidotExE (https://sketchfab.com/ParuthidotExE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-art-026-teleporting-human-19f29fe2657d456282b9dac333b6bfdb
Title: Modern Art 026 Teleporting Human
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Mesh|MeshAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Mesh_Material001_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='RootNode' scale={0.005}>
          <group name='Mesh' rotation={[-Math.PI / 2, 0, 0.501]} scale={100}>
            <mesh
              name='Mesh_Material001_0'
              castShadow
              receiveShadow
              geometry={nodes.Mesh_Material001_0.geometry}
              material={materials['Material.001']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
