/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 untitled.glb --transform --instance -ts 
Files: untitled.glb [12.18MB] > /home/necron/Web/rasta-rock-ecommerce/apps/next/public/models/AbstractBg/untitled-transformed.glb [2.84MB] (77%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Mesh|MeshAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Mesh_Material001_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/untitled-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" scale={0.005}>
          <group name="Mesh" rotation={[-Math.PI / 2, 0, 0.501]} scale={100}>
            <mesh name="Mesh_Material001_0" castShadow receiveShadow geometry={nodes.Mesh_Material001_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/untitled-transformed.glb')
